// src/Paginas/Perfil/MisCursos.tsx
import React, { useEffect, useState } from 'react'
import GridMisCursos from '../../componentes/MisCursos/GridMisCursos'
import PorcentajePerfil from '../../componentes/Perfil/PorcentajePerfil'
import BannerSlider from '../../componentes/Banners/BannerSlider'
import { usePerfilStore } from '../../stores/perfilStore'
import { supabase } from '../../servicios/supabaseCliente'

import { useUsuario } from '../../contextos/UsuarioContext'

export default function MisCursos() {
  const { perfil } = usePerfilStore()
  const { usuario } = useUsuario()
  const [inscripciones, setInscripciones] = useState<any[]>([])
  const [cargandoCursos, setCargandoCursos] = useState(true)
  const [errorCursos, setErrorCursos] = useState<string | null>(null)

  async function cargarInscripciones() {
    if (!usuario) return

    try {
      setCargandoCursos(true); setErrorCursos(null)

      // Promesa de carga con los datos
      const fetchPromise = async () => {
        const { data: insc, error } = await supabase.from('inscripciones').select('*').eq('usuario_id', usuario.id).order('fecha_inscripcion', { ascending: false })
        if (error) throw error
        return insc
      }

      // Timeout de 5 segundos
      const timeoutPromise = new Promise((_, reject) => setTimeout(() => reject(new Error('Tiempo de espera agotado al cargar cursos')), 5000))

      const insc = await Promise.race([fetchPromise(), timeoutPromise]) as any[]

      if (!insc || !insc.length) { setInscripciones([]); return }
      const insCursos = insc.filter((i: any) => i.curso_id)
      const insTuts = insc.filter((i: any) => i.tutorial_id)
      let cursosData: any[] = [], tutorialesData: any[] = []

      // Parallel fetches for details (also could benefit from timeout but let's secure the main first)
      if (insCursos.length) { const ids = insCursos.map((i: any) => i.curso_id); const { data } = await supabase.from('cursos').select('id, titulo, descripcion, imagen_url, nivel, duracion_estimada, precio_normal, slug').in('id', ids); cursosData = data || [] }
      if (insTuts.length) { const ids = insTuts.map((i: any) => i.tutorial_id); const { data } = await supabase.from('tutoriales').select('id, titulo, descripcion, imagen_url, nivel, duracion_estimada, precio_normal, artista, acordeonista, tonalidad').in('id', ids); tutorialesData = data || [] }

      const combinadas = [
        ...insCursos.map((ins: any) => ({ ...ins, cursos: cursosData.find((c: any) => c.id === ins.curso_id) })),
        ...insTuts.map((ins: any) => ({ ...ins, tutoriales: tutorialesData.find((t: any) => t.id === ins.tutorial_id) }))
      ].sort((a: any, b: any) => new Date(b.fecha_inscripcion).getTime() - new Date(a.fecha_inscripcion).getTime())

      setInscripciones(combinadas)
    } catch (e: any) {
      console.error('Error cargando cursos:', e)
      setErrorCursos(e.message || 'Error desconocido al cargar los cursos')
    } finally {
      setCargandoCursos(false)
    }
  }

  useEffect(() => {
    if (usuario) {
      cargarInscripciones()
    }
  }, [usuario])

  return (
    <div className="contenido-mis-cursos">
      <div className="layout-mis-cursos" style={{ display: 'grid', gridTemplateColumns: '1fr 320px', gap: '2rem', alignItems: 'start', overflow: 'hidden' }}>
        <div className="columna-principal" style={{ minWidth: 0, overflow: 'hidden' }}>
          <div className="header-mis-cursos" style={{ marginBottom: '2rem', display: 'block' }}>
            <h1 style={{ fontSize: '2rem', fontWeight: 700, color: '#1f2937', margin: '0 0 .5rem 0' }}>Mis Cursos</h1>
            <p style={{ color: '#6b7280', fontSize: '1.1rem' }}>Continúa con tu aprendizaje de acordeón vallenato</p>
          </div>
          <GridMisCursos inscripciones={inscripciones} isLoading={cargandoCursos} error={errorCursos} />
        </div>
        <aside className="columna-lateral" style={{ width: 320, maxWidth: 320 }}>
          <div className="widgets-contenedor" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', width: '100%', maxWidth: '100%', overflow: 'hidden' }}>
            {perfil && (<PorcentajePerfil perfil={perfil} />)}
            <BannerSlider />
          </div>
        </aside>
      </div>
    </div>
  )
}

// src/routes/(perfil)/mis-cursos/+page.svelte
<script lang="ts">
  import GridMisCursos from '$lib/components/MisCursos/GridMisCursos.svelte';
  import PorcentajePerfil from '$lib/components/Banners/PorcentajePerfil.svelte';
  import BannerSlider from '$lib/components/Banners/BannerSlider.svelte';
  import { perfilStore } from '$lib/stores/perfilStore';
  import { usuario } from '$lib/UsuarioActivo/usuario';
  import { supabase } from '$lib/supabase/clienteSupabase';
  import { onMount } from 'svelte';

  // Usar datos del store en lugar de cargar por separado
  $: perfilData = $perfilStore.perfil;
  $: cargandoPerfil = $perfilStore.cargando;

  // Estados para las inscripciones
  let inscripciones: any[] = [];
  let cargandoCursos = true;
  let errorCursos: string | null = null;

  async function cargarInscripciones() {
    if (!$usuario?.id) {
      cargandoCursos = false;
      return;
    }

    try {
      cargandoCursos = true;
      errorCursos = null;

      // Primero obtener todas las inscripciones del usuario
      const { data: inscripcionesData, error } = await supabase
        .from('inscripciones')
        .select('*')
        .eq('usuario_id', $usuario.id)
        .order('fecha_inscripcion', { ascending: false });

      if (error) {
        throw error;
      }

      if (!inscripcionesData || inscripcionesData.length === 0) {
        inscripciones = [];
        return;
      }

      // Separar las inscripciones por tipo
      const inscripcionesCursos = inscripcionesData.filter((i: any) => i.curso_id);
      const inscripcionesTutoriales = inscripcionesData.filter((i: any) => i.tutorial_id);

      // Obtener datos de cursos si hay inscripciones a cursos
      let cursosData = [];
      if (inscripcionesCursos.length > 0) {
        const cursoIds = inscripcionesCursos.map((i: any) => i.curso_id);
        const { data: cursos } = await supabase
          .from('cursos')
          .select('id, titulo, descripcion, imagen_url, nivel, duracion_estimada, precio_normal, slug')
          .in('id', cursoIds);
        cursosData = cursos || [];
      }

      // Obtener datos de tutoriales si hay inscripciones a tutoriales
      let tutorialesData = [];
      if (inscripcionesTutoriales.length > 0) {
        const tutorialIds = inscripcionesTutoriales.map((i: any) => i.tutorial_id);
        const { data: tutoriales } = await supabase
          .from('tutoriales')
          .select('id, titulo, descripcion, imagen_url, nivel, duracion_estimada, precio_normal, artista, acordeonista, tonalidad')
          .in('id', tutorialIds);
        tutorialesData = tutoriales || [];
      }

      // Combinar todo
      inscripciones = [
        // Inscripciones a cursos
        ...inscripcionesCursos.map((inscripcion: any) => ({
          ...inscripcion,
          cursos: cursosData.find((curso: any) => curso.id === inscripcion.curso_id)
        })),
        // Inscripciones a tutoriales
        ...inscripcionesTutoriales.map((inscripcion: any) => ({
          ...inscripcion,
          tutoriales: tutorialesData.find((tutorial: any) => tutorial.id === inscripcion.tutorial_id)
        }))
      ];

      // Reordenar por fecha de inscripción
      inscripciones.sort((a, b) => new Date(b.fecha_inscripcion).getTime() - new Date(a.fecha_inscripcion).getTime());
    } catch (error: any) {
      console.error('Error cargando inscripciones:', error);
      errorCursos = error.message || 'Error desconocido al cargar los cursos';
    } finally {
      cargandoCursos = false;
    }
  }

  onMount(() => {
    cargarInscripciones();
  });

  // Recargar cuando cambie el usuario
  $: if ($usuario?.id) {
    cargarInscripciones();
  }
</script>

<svelte:head>
  <title>Mis Cursos - Academia Vallenata</title>
  <meta name="description" content="Accede a todos tus cursos de acordeón vallenato" />
</svelte:head>

<div class="contenido-mis-cursos">
  <div class="layout-mis-cursos">
    <div class="columna-principal">
      <div class="header-seccion">
        <h1>Mis Cursos</h1>
        <p>Continúa con tu aprendizaje de acordeón vallenato</p>
      </div>
      
      <!-- Pasar las props necesarias a GridMisCursos -->
      <GridMisCursos 
        {inscripciones}
        isLoading={cargandoCursos}
        error={errorCursos}
      />
    </div>
    
    <aside class="columna-lateral">
      <div class="widgets-contenedor">
        {#if perfilData}
          <PorcentajePerfil perfil={perfilData} />
        {/if}
        <BannerSlider />
      </div>
    </aside>
  </div>
</div>

<style>
  .contenido-mis-cursos {
    padding: 2rem;
  }

  .layout-mis-cursos {
    display: grid;
    grid-template-columns: 2fr 1fr;
    gap: 2.5rem;
    align-items: start;
  }

  .columna-principal {
    min-width: 0;
  }

  .header-seccion {
    margin-bottom: 2rem;
  }

  .header-seccion h1 {
    font-size: 2rem;
    font-weight: 700;
    color: #1f2937;
    margin-bottom: 0.5rem;
  }

  .header-seccion p {
    color: #6b7280;
    font-size: 1.1rem;
  }

  .columna-lateral {
    position: sticky;
    top: 2rem;
  }

  .widgets-contenedor {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  @media (max-width: 900px) {
    .contenido-mis-cursos {
      padding: 1.5rem;
    }

    .layout-mis-cursos {
      grid-template-columns: 1fr;
      gap: 2rem;
    }

    .columna-lateral {
      order: 1;
      position: static;
    }

    .columna-principal {
      order: 0;
    }
  }

  @media (max-width: 640px) {
    .contenido-mis-cursos {
      padding: 1rem;
    }
    
    .header-seccion h1 {
      font-size: 1.75rem;
    }
  }
</style>
