// src/Paginas/Eventos/Componentes/CalendarioEventos.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { eventosService, type EventoCompleto } from '../../../servicios/eventosService';
import './CalendarioEventos.css';

// Usamos el tipo del servicio
type Evento = EventoCompleto;

interface CalendarioEventosProps {
    vistaInicial?: 'grid' | 'lista';
    mostrarFiltros?: boolean;
    eventosPorPagina?: number;
}

const CalendarioEventos: React.FC<CalendarioEventosProps> = ({
    vistaInicial = 'grid',
    mostrarFiltros = true,
    eventosPorPagina = 12
}) => {
    const navigate = useNavigate();
    const [vista, setVista] = useState<'grid' | 'lista'>(vistaInicial);
    const [eventos, setEventos] = useState<Evento[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [paginaActual, setPaginaActual] = useState(0);
    const [totalPaginas, setTotalPaginas] = useState(0);

    // Filtros
    const [filtros, setFiltros] = useState({
        categoria: '',
        tipo_evento: '',
        nivel_dificultad: '',
        es_gratuito: undefined as boolean | undefined,
        busqueda: '',
        fecha_desde: '',
        fecha_hasta: ''
    });

    const categorias = [
        { value: '', label: 'Todas las categorías' },
        { value: 'tecnica', label: 'Técnica' },
        { value: 'teoria', label: 'Teoría' },
        { value: 'repertorio', label: 'Repertorio' },
        { value: 'historia', label: 'Historia' }
    ];

    const tiposEvento = [
        { value: '', label: 'Todos los tipos' },
        { value: 'masterclass', label: 'Masterclass' },
        { value: 'workshop', label: 'Workshop' },
        { value: 'concierto', label: 'Concierto' },
        { value: 'concurso', label: 'Concurso' },
        { value: 'webinar', label: 'Webinar' },
        { value: 'reunion', label: 'Reunión' }
    ];

    const nivelesEvento = [
        { value: '', label: 'Todos los niveles' },
        { value: 'principiante', label: 'Principiante' },
        { value: 'intermedio', label: 'Intermedio' },
        { value: 'avanzado', label: 'Avanzado' },
        { value: 'profesional', label: 'Profesional' }
    ];

    const cargarEventos = async () => {
        setLoading(true);
        setError(null);
        try {
            // @ts-ignore - Asumimos compatibilidad con el servicio existente
            const { eventos: eventosData, total, error: errorData } = await eventosService.obtenerEventos({
                ...filtros,
                estado: 'programado',
                limit: eventosPorPagina,
                offset: paginaActual * eventosPorPagina
            });

            if (errorData) {
                setError(errorData);
                return;
            }

            setEventos(eventosData || []);
            // setTotalEventos(total || 0); // Unused
            setTotalPaginas(Math.ceil((total || 0) / eventosPorPagina));
        } catch (err: any) {
            setError(err.message || 'Error desconocido');
            console.error('Error cargando eventos:', err);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        cargarEventos();
    }, [paginaActual, filtros]);
    // Nota: en React, agregar filtros aquí dispara la recarga. 
    // En Svelte se llamaba aplicarFiltros explícitamente. 
    // Aquí usamos el efecto para reactividad automática.

    const handleFiltroChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        const { name, value, type } = e.target;
        if (type === 'checkbox') {
            const checked = (e.target as HTMLInputElement).checked;
            setFiltros(prev => ({ ...prev, [name]: checked ? true : undefined }));
        } else {
            setFiltros(prev => ({ ...prev, [name]: value }));
        }
        setPaginaActual(0); // Reset página al filtrar
    };

    const limpiarFiltros = () => {
        setFiltros({
            categoria: '',
            tipo_evento: '',
            nivel_dificultad: '',
            es_gratuito: undefined,
            busqueda: '',
            fecha_desde: '',
            fecha_hasta: ''
        });
        setPaginaActual(0);
    };

    const formatearFecha = (fecha: string): string => {
        return new Date(fecha).toLocaleDateString('es-ES', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });
    };

    const formatearHora = (fecha: string): string => {
        return new Date(fecha).toLocaleTimeString('es-ES', {
            hour: '2-digit',
            minute: '2-digit'
        });
    };

    const formatearPrecio = (precio: number): string => {
        return new Intl.NumberFormat('es-CO', {
            style: 'currency',
            currency: 'COP',
            minimumFractionDigits: 0
        }).format(precio);
    };

    const obtenerColorTipo = (tipo: string): string => {
        // Mapeo manual a estilos inline para simplificar la migración de colores dynamic
        const colorMap: Record<string, string> = {
            masterclass: '#dbeafe #1e40af', // bg-blue-100 text-blue-800
            workshop: '#dcfce7 #166534',
            concierto: '#f3e8ff #6b21a8',
            concurso: '#ffedd5 #9a3412',
            webinar: '#e0e7ff #3730a3',
            reunion: '#f3f4f6 #1f2937'
        };
        return colorMap[tipo] || '#f3f4f6 #1f2937';
    };

    const getBadgeStyle = (tipo: string) => {
        const styles = obtenerColorTipo(tipo).split(' ');
        return { backgroundColor: styles[0], color: styles[1] };
    };

    const obtenerColorNivel = (nivel: string): string => {
        const colores: Record<string, string> = {
            principiante: '#22c55e',
            intermedio: '#eab308',
            avanzado: '#f97316',
            profesional: '#ef4444'
        };
        return colores[nivel] || '#6b7280';
    };

    return (
        <div className="evt-cal-container">
            {/* Header */}
            <div className="evt-cal-header">
                <div className="evt-cal-title-section">
                    <h1 className="evt-cal-title">📅 Calendario de Eventos</h1>
                    <p className="evt-cal-subtitle">Descubre masterclasses, workshops y eventos especiales de acordeón</p>
                </div>

                <div className="evt-cal-view-toggle">
                    <button
                        className={`evt-cal-view-btn ${vista === 'grid' ? 'active' : ''}`}
                        onClick={() => setVista('grid')}
                    >
                        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24" style={{ width: '1rem', height: '1rem' }}>
                            <rect x="3" y="3" width="7" height="7"></rect>
                            <rect x="14" y="3" width="7" height="7"></rect>
                            <rect x="14" y="14" width="7" height="7"></rect>
                            <rect x="3" y="14" width="7" height="7"></rect>
                        </svg>
                        Grid
                    </button>
                    <button
                        className={`evt-cal-view-btn ${vista === 'lista' ? 'active' : ''}`}
                        onClick={() => setVista('lista')}
                    >
                        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24" style={{ width: '1rem', height: '1rem' }}>
                            <path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"></path>
                        </svg>
                        Lista
                    </button>
                </div>
            </div>

            {/* Filtros */}
            {mostrarFiltros && (
                <div className="evt-cal-filters-container">
                    <div className="evt-cal-filters-header">
                        <h3 className="evt-cal-filters-title">
                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" style={{ width: '1.25rem' }}>
                                <polygon points="22,3 2,3 10,12.46 10,19 14,21 14,12.46 22,3" />
                            </svg>
                            Filtros
                        </h3>
                        <button className="evt-cal-clear-filters" onClick={limpiarFiltros}>
                            Limpiar filtros
                        </button>
                    </div>

                    <div className="evt-cal-filters-grid">
                        <div className="evt-cal-filter-group-wide">
                            <label className="evt-cal-label">Buscar eventos</label>
                            <input
                                type="text"
                                name="busqueda"
                                placeholder="Busca por título o descripción..."
                                className="evt-cal-input"
                                value={filtros.busqueda}
                                onChange={handleFiltroChange}
                            />
                        </div>

                        <div>
                            <label className="evt-cal-label">Categoría</label>
                            <select
                                name="categoria"
                                className="evt-cal-select"
                                value={filtros.categoria}
                                onChange={handleFiltroChange}
                            >
                                {categorias.map(c => <option key={c.value} value={c.value}>{c.label}</option>)}
                            </select>
                        </div>

                        <div>
                            <label className="evt-cal-label">Tipo</label>
                            <select
                                name="tipo_evento"
                                className="evt-cal-select"
                                value={filtros.tipo_evento}
                                onChange={handleFiltroChange}
                            >
                                {tiposEvento.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}
                            </select>
                        </div>

                        <div>
                            <label className="evt-cal-label">Nivel</label>
                            <select
                                name="nivel_dificultad"
                                className="evt-cal-select"
                                value={filtros.nivel_dificultad}
                                onChange={handleFiltroChange}
                            >
                                {nivelesEvento.map(n => <option key={n.value} value={n.value}>{n.label}</option>)}
                            </select>
                        </div>

                        <div className="evt-cal-checkbox-group">
                            <input
                                type="checkbox"
                                name="es_gratuito"
                                id="solo-gratuitos"
                                className="evt-cal-checkbox"
                                checked={filtros.es_gratuito === true}
                                onChange={handleFiltroChange}
                            />
                            <label htmlFor="solo-gratuitos" className="evt-cal-checkbox-label">
                                Solo eventos gratuitos
                            </label>
                        </div>

                        <div>
                            <label className="evt-cal-label">Desde</label>
                            <input
                                type="date"
                                name="fecha_desde"
                                className="evt-cal-input"
                                value={filtros.fecha_desde}
                                onChange={handleFiltroChange}
                            />
                        </div>
                    </div>
                </div>
            )}

            {/* Loading */}
            {loading ? (
                <div className="evt-cal-loading">
                    <div className="evt-cal-spinner"></div>
                </div>
            ) : error ? (
                <div className="evt-cal-error-container">
                    <div>❌ Error cargando eventos</div>
                    <p>{error}</p>
                    <button className="evt-cal-page-btn" onClick={cargarEventos} style={{ marginTop: '1rem' }}>
                        Reintentar
                    </button>
                </div>
            ) : (
                <>
                    {eventos.length === 0 ? (
                        <div className="evt-cal-empty">
                            <svg className="w-16 h-16 mx-auto mb-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" style={{ width: '4rem', color: '#9ca3af' }}>
                                <rect x="3" y="4" width="18" height="18" rx="2" ry="2" />
                                <line x1="16" y1="2" x2="16" y2="6" />
                                <line x1="8" y1="2" x2="8" y2="6" />
                                <line x1="3" y1="10" x2="21" y2="10" />
                            </svg>
                            <h3 className="evt-cal-title" style={{ fontSize: '1.25rem' }}>No hay eventos</h3>
                            <p className="evt-cal-subtitle">No se encontraron eventos con los filtros seleccionados.</p>
                        </div>
                    ) : (
                        vista === 'grid' ? (
                            <div className="evt-cal-grid-layout">
                                {eventos.map(evento => (
                                    <div
                                        key={evento.id}
                                        className="evt-cal-card"
                                        onClick={() => navigate(`/eventos/${evento.slug}`)}
                                    >
                                        <div className="evt-cal-card-img-container">
                                            {evento.imagen_portada ? (
                                                <img src={evento.imagen_portada} alt={evento.titulo} className="evt-cal-card-img" />
                                            ) : (
                                                <div className="evt-cal-card-img" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white' }}>
                                                    <svg className="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24" style={{ width: '4rem' }}>
                                                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2" />
                                                    </svg>
                                                </div>
                                            )}

                                            <div className="evt-cal-badges">
                                                <span className="evt-cal-badge" style={getBadgeStyle(evento.tipo_evento)}>
                                                    {evento.tipo_evento}
                                                </span>
                                                {evento.es_gratuito && (
                                                    <span className="evt-cal-badge-free">GRATIS</span>
                                                )}
                                                {evento.es_destacado && (
                                                    <span className="evt-cal-badge-featured">
                                                        ★ Destacado
                                                    </span>
                                                )}
                                            </div>

                                            {evento.nivel_dificultad && (
                                                <div className="evt-cal-level-indicator" style={{ backgroundColor: obtenerColorNivel(evento.nivel_dificultad) }}></div>
                                            )}
                                        </div>

                                        <div className="evt-cal-card-body">
                                            <h3 className="evt-cal-card-title">{evento.titulo}</h3>
                                            {evento.descripcion_corta && (
                                                <p className="evt-cal-card-desc">{evento.descripcion_corta}</p>
                                            )}

                                            <div className="evt-cal-card-info">
                                                <div className="evt-cal-info-item">
                                                    <span>📅 {formatearFecha(evento.fecha_inicio)}</span>
                                                </div>
                                                <div className="evt-cal-info-item">
                                                    <span>⏰ {formatearHora(evento.fecha_inicio)}</span>
                                                </div>
                                                <div className="evt-cal-info-item">
                                                    <span>📍 {evento.modalidad === 'online' ? 'En línea' : 'Presencial'}</span>
                                                </div>
                                            </div>

                                            <div className="evt-cal-card-footer">
                                                <div>
                                                    {evento.es_gratuito ? (
                                                        <span className="evt-cal-price-free">Gratis</span>
                                                    ) : (
                                                        <div style={{ display: 'flex', flexDirection: 'column' }}>
                                                            {evento.precio_rebajado && evento.precio_rebajado < evento.precio ? (
                                                                <>
                                                                    <span className="evt-cal-price-original">{formatearPrecio(evento.precio)}</span>
                                                                    <span className="evt-cal-price">{formatearPrecio(evento.precio_rebajado)}</span>
                                                                </>
                                                            ) : (
                                                                <span className="evt-cal-price">{formatearPrecio(evento.precio)}</span>
                                                            )}
                                                        </div>
                                                    )}
                                                </div>

                                                <div className="evt-cal-stats">
                                                    <span>👥 {evento.participantes_inscritos}</span>
                                                    {evento.calificacion_promedio > 0 && <span>⭐ {evento.calificacion_promedio.toFixed(1)}</span>}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        ) : (
                            <div className="evt-cal-list-container">
                                {/* IMPLEMENTAR LISTA SI ES NECESARIO, POR AHORA USAR CARD SIMPLIFICADA O REUTILIZAR ESTRUCTURA */}
                                {eventos.map(evento => (
                                    <div
                                        key={evento.id}
                                        className="evt-cal-list-card"
                                        onClick={() => navigate(`/eventos/${evento.slug}`)}
                                    >
                                        <div className="evt-cal-list-body">
                                            <div className="evt-cal-list-flex">
                                                <div className="evt-cal-list-img">
                                                    {evento.imagen_portada && <img src={evento.imagen_portada} alt={evento.titulo} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />}
                                                </div>

                                                <div className="evt-cal-list-content">
                                                    <h3 className="evt-cal-card-title" style={{ fontSize: '1.25rem' }}>{evento.titulo}</h3>
                                                    <p className="evt-cal-subtitle" style={{ marginBottom: '0.5rem' }}>{evento.descripcion_corta}</p>

                                                    <div className="evt-cal-info-item">
                                                        <span>📅 {formatearFecha(evento.fecha_inicio)} • ⏰ {formatearHora(evento.fecha_inicio)} • {evento.modalidad}</span>
                                                    </div>
                                                </div>

                                                <div className="evt-cal-list-sidebar">
                                                    <span className="evt-cal-badge" style={getBadgeStyle(evento.tipo_evento)}>{evento.tipo_evento}</span>
                                                    {evento.es_gratuito ? <span className="evt-cal-price-free">Gratis</span> : <span className="evt-cal-price">{formatearPrecio(evento.precio)}</span>}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        )
                    )}

                    {/* Paginación */}
                    {totalPaginas > 1 && (
                        <div className="evt-cal-pagination">
                            <button
                                className="evt-cal-page-btn"
                                disabled={paginaActual === 0}
                                onClick={() => setPaginaActual(p => p - 1)}
                            >
                                Anterior
                            </button>

                            {Array.from({ length: totalPaginas }).map((_, i) => (
                                (i === 0 || i === totalPaginas - 1 || (i >= paginaActual - 1 && i <= paginaActual + 1)) ? (
                                    <button
                                        key={i}
                                        className={`evt-cal-page-btn ${i === paginaActual ? 'active' : ''}`}
                                        onClick={() => setPaginaActual(i)}
                                    >
                                        {i + 1}
                                    </button>
                                ) : (
                                    (i === paginaActual - 2 || i === paginaActual + 2) && <span key={i}>...</span>
                                )
                            ))}

                            <button
                                className="evt-cal-page-btn"
                                disabled={paginaActual === totalPaginas - 1}
                                onClick={() => setPaginaActual(p => p + 1)}
                            >
                                Siguiente
                            </button>
                        </div>
                    )}
                </>
            )}
        </div>
    );
};

export default CalendarioEventos;

// src/lib/components/Eventos/CalendarioEventos.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { eventosService, type Evento } from '$lib/services/eventosService';
  import { usuario } from '$lib/UsuarioActivo/usuario';
  
  // Props
  export let vista: 'calendario' | 'grid' | 'lista' = 'grid';
  export let mostrarFiltros: boolean = true;
  export let eventosPorPagina: number = 12;
  
  // Estado del componente
  let eventos: Evento[] = [];
  let loading = true;
  let error: string | null = null;
  let paginaActual = 0;
  let totalEventos = 0;
  let totalPaginas = 0;
  
  // Filtros
  let filtros = {
    categoria: '',
    tipo_evento: '',
    nivel_dificultad: '',
    es_gratuito: undefined as boolean | undefined,
    busqueda: '',
    fecha_desde: '',
    fecha_hasta: ''
  };
  
  // Opciones para filtros
  const categorias = [
    { value: '', label: 'Todas las categorías' },
    { value: 'tecnica', label: 'Técnica' },
    { value: 'teoria', label: 'Teoría' },
    { value: 'repertorio', label: 'Repertorio' },
    { value: 'historia', label: 'Historia' }
  ];
  
  const tiposEvento = [
    { value: '', label: 'Todos los tipos' },
    { value: 'masterclass', label: 'Masterclass' },
    { value: 'workshop', label: 'Workshop' },
    { value: 'concierto', label: 'Concierto' },
    { value: 'concurso', label: 'Concurso' },
    { value: 'webinar', label: 'Webinar' },
    { value: 'reunion', label: 'Reunión' }
  ];
  
  const nivelesEvento = [
    { value: '', label: 'Todos los niveles' },
    { value: 'principiante', label: 'Principiante' },
    { value: 'intermedio', label: 'Intermedio' },
    { value: 'avanzado', label: 'Avanzado' },
    { value: 'profesional', label: 'Profesional' }
  ];

  // Funciones de utilidad
  function formatearFecha(fecha: string): string {
    return new Date(fecha).toLocaleDateString('es-ES', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  }
  
  function formatearHora(fecha: string): string {
    return new Date(fecha).toLocaleTimeString('es-ES', {
      hour: '2-digit',
      minute: '2-digit'
    });
  }
  
  function formatearPrecio(precio: number): string {
    return new Intl.NumberFormat('es-CO', {
      style: 'currency',
      currency: 'COP',
      minimumFractionDigits: 0
    }).format(precio);
  }
  
  function obtenerColorTipo(tipo: string): string {
    const colores: Record<string, string> = {
      masterclass: 'bg-blue-100 text-blue-800',
      workshop: 'bg-green-100 text-green-800',
      concierto: 'bg-purple-100 text-purple-800',
      concurso: 'bg-orange-100 text-orange-800',
      webinar: 'bg-indigo-100 text-indigo-800',
      reunion: 'bg-gray-100 text-gray-800'
    };
    return colores[tipo] || 'bg-gray-100 text-gray-800';
  }
  
  function obtenerColorNivel(nivel: string): string {
    const colores: Record<string, string> = {
      principiante: 'bg-green-500',
      intermedio: 'bg-yellow-500',
      avanzado: 'bg-orange-500',
      profesional: 'bg-red-500'
    };
    return colores[nivel] || 'bg-gray-500';
  }
  
  // Funciones principales
  async function cargarEventos(): Promise<void> {
    loading = true;
    error = null;
    
    try {
      const { eventos: eventosData, total, error: errorData } = await eventosService.obtenerEventos({
        ...filtros,
        estado: 'programado',
        limit: eventosPorPagina,
        offset: paginaActual * eventosPorPagina
      });
      
      if (errorData) {
        error = errorData;
        return;
      }
      
      eventos = eventosData;
      totalEventos = total;
      totalPaginas = Math.ceil(total / eventosPorPagina);
    } catch (err: any) {
      error = err.message || 'Error desconocido';
      console.error('Error cargando eventos:', err);
    } finally {
      loading = false;
    }
  }
  
  function aplicarFiltros(): void {
    paginaActual = 0;
    cargarEventos();
  }
  
  function limpiarFiltros(): void {
    filtros = {
      categoria: '',
      tipo_evento: '',
      nivel_dificultad: '',
      es_gratuito: undefined,
      busqueda: '',
      fecha_desde: '',
      fecha_hasta: ''
    };
    aplicarFiltros();
  }
  
  function cambiarPagina(nuevaPagina: number): void {
    paginaActual = nuevaPagina;
    cargarEventos();
  }
  
  function irAEvento(slug: string): void {
    window.location.href = `/eventos/${slug}`;
  }
  
  // Cargar eventos al montar el componente
  onMount(() => {
    cargarEventos();
  });
</script>

<!-- Componente Principal -->
<div class="w-full max-w-7xl mx-auto p-6 bg-white">
  <!-- Header con títulos y controles de vista -->
  <div class="flex flex-col lg:flex-row lg:items-center lg:justify-between mb-8">
    <div class="mb-4 lg:mb-0">
      <h1 class="text-3xl font-bold text-gray-900 mb-2">
        📅 Calendario de Eventos
      </h1>
      <p class="text-gray-600">
        Descubre masterclasses, workshops y eventos especiales de acordeón
      </p>
    </div>
    
    <!-- Selector de vista -->
    <div class="flex bg-gray-100 rounded-lg p-1">
      <button
        class="px-4 py-2 rounded-md text-sm font-medium transition-all {vista === 'grid' ? 'bg-white text-blue-600 shadow-sm' : 'text-gray-600 hover:text-gray-900'}"
        on:click={() => vista = 'grid'}
      >
        <div class="flex items-center gap-2">
          <div class="w-4 h-4 grid grid-cols-2 gap-0.5">
            <div class="bg-current rounded-sm"></div>
            <div class="bg-current rounded-sm"></div>
            <div class="bg-current rounded-sm"></div>
            <div class="bg-current rounded-sm"></div>
          </div>
          Grid
        </div>
      </button>
      <button
        class="px-4 py-2 rounded-md text-sm font-medium transition-all {vista === 'lista' ? 'bg-white text-blue-600 shadow-sm' : 'text-gray-600 hover:text-gray-900'}"
        on:click={() => vista = 'lista'}
      >
        <div class="flex items-center gap-2">
          <div class="flex flex-col gap-0.5">
            <div class="w-4 h-0.5 bg-current rounded"></div>
            <div class="w-4 h-0.5 bg-current rounded"></div>
            <div class="w-4 h-0.5 bg-current rounded"></div>
          </div>
          Lista
        </div>
      </button>
    </div>
  </div>
  
  <!-- Filtros -->
  {#if mostrarFiltros}
    <div class="bg-gray-50 rounded-xl p-6 mb-8">
      <div class="flex items-center justify-between mb-4">
        <h3 class="text-lg font-semibold text-gray-900 flex items-center gap-2">
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <polygon points="22,3 2,3 10,12.46 10,19 14,21 14,12.46 22,3"/>
          </svg>
          Filtros
        </h3>
        <button
          class="text-sm text-blue-600 hover:text-blue-800 font-medium"
          on:click={limpiarFiltros}
        >
          Limpiar filtros
        </button>
      </div>
      
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6 gap-4">
        <!-- Búsqueda -->
        <div class="xl:col-span-2">
          <label class="block text-sm font-medium text-gray-700 mb-2">
            Buscar eventos
          </label>
          <input
            type="text"
            placeholder="Busca por título o descripción..."
            class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            bind:value={filtros.busqueda}
            on:input={aplicarFiltros}
          />
        </div>
        
        <!-- Categoría -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">Categoría</label>
          <select
            class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            bind:value={filtros.categoria}
            on:change={aplicarFiltros}
          >
            {#each categorias as categoria}
              <option value={categoria.value}>{categoria.label}</option>
            {/each}
          </select>
        </div>
        
        <!-- Tipo -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">Tipo</label>
          <select
            class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            bind:value={filtros.tipo_evento}
            on:change={aplicarFiltros}
          >
            {#each tiposEvento as tipo}
              <option value={tipo.value}>{tipo.label}</option>
            {/each}
          </select>
        </div>
        
        <!-- Nivel -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">Nivel</label>
          <select
            class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            bind:value={filtros.nivel_dificultad}
            on:change={aplicarFiltros}
          >
            {#each nivelesEvento as nivel}
              <option value={nivel.value}>{nivel.label}</option>
            {/each}
          </select>
        </div>
        
        <!-- Solo gratuitos -->
        <div class="flex items-center pt-6">
          <input
            type="checkbox"
            id="solo-gratuitos"
            class="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
            checked={filtros.es_gratuito === true}
            on:change={(e) => {
              const target = e.target as HTMLInputElement;
              filtros.es_gratuito = target?.checked ? true : undefined;
              aplicarFiltros();
            }}
          />
          <label for="solo-gratuitos" class="ml-2 text-sm text-gray-700">
            Solo eventos gratuitos
          </label>
        </div>
        
        <!-- Fecha desde -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">Desde</label>
          <input
            type="date"
            class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            bind:value={filtros.fecha_desde}
            on:change={aplicarFiltros}
          />
        </div>
      </div>
    </div>
  {/if}
  
  <!-- Loading -->
  {#if loading}
    <div class="flex items-center justify-center py-12">
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
    </div>
  <!-- Error -->
  {:else if error}
    <div class="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
      <div class="text-red-600 mb-2">❌ Error cargando eventos</div>
      <p class="text-red-700">{error}</p>
      <button
        class="mt-4 px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
        on:click={cargarEventos}
      >
        Reintentar
      </button>
    </div>
  <!-- Contenido -->
  {:else}
    <!-- Vista Grid -->
    {#if vista === 'grid'}
      {#if eventos.length === 0}
        <div class="text-center py-12">
          <svg class="w-16 h-16 text-gray-400 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <rect x="3" y="4" width="18" height="18" rx="2" ry="2"/>
            <line x1="16" y1="2" x2="16" y2="6"/>
            <line x1="8" y1="2" x2="8" y2="6"/>
            <line x1="3" y1="10" x2="21" y2="10"/>
          </svg>
          <h3 class="text-xl font-semibold text-gray-900 mb-2">No hay eventos</h3>
          <p class="text-gray-600">No se encontraron eventos con los filtros seleccionados.</p>
        </div>
      {:else}
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 mb-8">
          {#each eventos as evento}
            <div class="bg-white rounded-xl shadow-md hover:shadow-xl transition-all duration-300 overflow-hidden group cursor-pointer" on:click={() => irAEvento(evento.slug)}>
              <!-- Imagen del evento -->
              <div class="relative h-48 bg-gradient-to-br from-blue-500 to-purple-600 overflow-hidden">
                {#if evento.imagen_portada}
                  <img
                    src={evento.imagen_portada}
                    alt={evento.titulo}
                    class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                  />
                {:else}
                  <div class="w-full h-full flex items-center justify-center text-white">
                    <svg class="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <rect x="3" y="4" width="18" height="18" rx="2" ry="2"/>
                      <line x1="16" y1="2" x2="16" y2="6"/>
                      <line x1="8" y1="2" x2="8" y2="6"/>
                      <line x1="3" y1="10" x2="21" y2="10"/>
                    </svg>
                  </div>
                {/if}
                
                <!-- Badges superiores -->
                <div class="absolute top-4 left-4 flex flex-col gap-2">
                  <span class="px-2 py-1 text-xs font-medium rounded-full {obtenerColorTipo(evento.tipo_evento)}">
                    {evento.tipo_evento}
                  </span>
                  {#if evento.es_gratuito}
                    <span class="px-2 py-1 text-xs font-bold bg-green-500 text-white rounded-full">
                      GRATIS
                    </span>
                  {/if}
                  {#if evento.es_destacado}
                    <span class="px-2 py-1 text-xs font-bold bg-yellow-500 text-white rounded-full flex items-center gap-1">
                      <svg class="w-3 h-3" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
                      </svg>
                      Destacado
                    </span>
                  {/if}
                </div>
                
                <!-- Nivel de dificultad -->
                {#if evento.nivel_dificultad}
                  <div class="absolute top-4 right-4">
                    <div class="w-3 h-3 rounded-full {obtenerColorNivel(evento.nivel_dificultad)}"></div>
                  </div>
                {/if}
              </div>
              
              <!-- Contenido de la tarjeta -->
              <div class="p-6">
                <h3 class="text-lg font-bold text-gray-900 mb-2 line-clamp-2 group-hover:text-blue-600 transition-colors">
                  {evento.titulo}
                </h3>
                
                {#if evento.descripcion_corta}
                  <p class="text-gray-600 text-sm mb-4 line-clamp-2">
                    {evento.descripcion_corta}
                  </p>
                {/if}
                
                <!-- Información del evento -->
                <div class="space-y-2 mb-4">
                  <div class="flex items-center gap-2 text-sm text-gray-600">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <rect x="3" y="4" width="18" height="18" rx="2" ry="2"/>
                      <line x1="16" y1="2" x2="16" y2="6"/>
                      <line x1="8" y1="2" x2="8" y2="6"/>
                      <line x1="3" y1="10" x2="21" y2="10"/>
                    </svg>
                    <span>{formatearFecha(evento.fecha_inicio)}</span>
                  </div>
                  
                  <div class="flex items-center gap-2 text-sm text-gray-600">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <circle cx="12" cy="12" r="10"/>
                      <polyline points="12,6 12,12 16,14"/>
                    </svg>
                    <span>{formatearHora(evento.fecha_inicio)}</span>
                    {#if evento.fecha_fin}
                      - {formatearHora(evento.fecha_fin)}
                    {/if}
                  </div>
                  
                  <div class="flex items-center gap-2 text-sm text-gray-600">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/>
                      <circle cx="12" cy="10" r="3"/>
                    </svg>
                    <span>{evento.modalidad === 'online' ? 'En línea' : evento.modalidad === 'presencial' ? 'Presencial' : 'Híbrido'}</span>
                  </div>
                  
                  {#if evento.instructor_nombre}
                    <div class="flex items-center gap-2 text-sm text-gray-600">
                      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/>
                        <circle cx="9" cy="7" r="4"/>
                        <path d="M23 21v-2a4 4 0 0 0-3-3.87"/>
                        <path d="M16 3.13a4 4 0 0 1 0 7.75"/>
                      </svg>
                      <span>Instructor: {evento.instructor_nombre}</span>
                    </div>
                  {/if}
                </div>
                
                <!-- Footer de la tarjeta -->
                <div class="flex items-center justify-between pt-4 border-t border-gray-100">
                  <!-- Precio -->
                  <div class="flex items-center gap-2">
                    {#if evento.es_gratuito}
                      <span class="text-lg font-bold text-green-600">Gratis</span>
                    {:else}
                      <div class="flex flex-col">
                        {#if evento.precio_rebajado && evento.precio_rebajado < evento.precio}
                          <span class="text-xs text-gray-500 line-through">
                            {formatearPrecio(evento.precio)}
                          </span>
                          <span class="text-lg font-bold text-blue-600">
                            {formatearPrecio(evento.precio_rebajado)}
                          </span>
                        {:else}
                          <span class="text-lg font-bold text-blue-600">
                            {formatearPrecio(evento.precio)}
                          </span>
                        {/if}
                      </div>
                    {/if}
                  </div>
                  
                  <!-- Estadísticas -->
                  <div class="flex items-center gap-3 text-sm text-gray-500">
                    <div class="flex items-center gap-1">
                      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/>
                        <circle cx="9" cy="7" r="4"/>
                        <path d="M23 21v-2a4 4 0 0 0-3-3.87"/>
                        <path d="M16 3.13a4 4 0 0 1 0 7.75"/>
                      </svg>
                      <span>{evento.participantes_inscritos}</span>
                    </div>
                    
                    {#if evento.calificacion_promedio > 0}
                      <div class="flex items-center gap-1">
                        <svg class="w-4 h-4 fill-yellow-400 text-yellow-400" viewBox="0 0 24 24">
                          <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
                        </svg>
                        <span>{evento.calificacion_promedio.toFixed(1)}</span>
                      </div>
                    {/if}
                    
                    {#if evento.total_visualizaciones > 0}
                      <div class="flex items-center gap-1">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
                          <circle cx="12" cy="12" r="3"/>
                        </svg>
                        <span>{evento.total_visualizaciones}</span>
                      </div>
                    {/if}
                  </div>
                </div>
              </div>
            </div>
          {/each}
        </div>
      {/if}
    
    <!-- Vista Lista -->
    {:else if vista === 'lista'}
      <div class="space-y-4 mb-8">
        {#each eventos as evento}
          <div class="bg-white rounded-xl shadow-md hover:shadow-lg transition-all duration-300 overflow-hidden group cursor-pointer" on:click={() => irAEvento(evento.slug)}>
            <div class="p-6">
              <div class="flex items-start gap-6">
                <!-- Imagen pequeña -->
                <div class="flex-shrink-0 w-24 h-24 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg overflow-hidden">
                  {#if evento.imagen_portada}
                    <img
                      src={evento.imagen_portada}
                      alt={evento.titulo}
                      class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                    />
                  {:else}
                    <div class="w-full h-full flex items-center justify-center text-white">
                      <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"/>
                        <line x1="16" y1="2" x2="16" y2="6"/>
                        <line x1="8" y1="2" x2="8" y2="6"/>
                        <line x1="3" y1="10" x2="21" y2="10"/>
                      </svg>
                    </div>
                  {/if}
                </div>
                
                <!-- Contenido -->
                <div class="flex-1 min-w-0">
                  <div class="flex items-start justify-between">
                    <div class="flex-1">
                      <h3 class="text-xl font-bold text-gray-900 mb-2 group-hover:text-blue-600 transition-colors">
                        {evento.titulo}
                      </h3>
                      
                      {#if evento.descripcion_corta}
                        <p class="text-gray-600 mb-4 line-clamp-2">
                          {evento.descripcion_corta}
                        </p>
                      {/if}
                      
                      <!-- Información del evento -->
                      <div class="flex flex-wrap gap-4 text-sm text-gray-600">
                        <div class="flex items-center gap-1">
                          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <rect x="3" y="4" width="18" height="18" rx="2" ry="2"/>
                            <line x1="16" y1="2" x2="16" y2="6"/>
                            <line x1="8" y1="2" x2="8" y2="6"/>
                            <line x1="3" y1="10" x2="21" y2="10"/>
                          </svg>
                          <span>{formatearFecha(evento.fecha_inicio)}</span>
                        </div>
                        
                        <div class="flex items-center gap-1">
                          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <circle cx="12" cy="12" r="10"/>
                            <polyline points="12,6 12,12 16,14"/>
                          </svg>
                          <span>{formatearHora(evento.fecha_inicio)}</span>
                        </div>
                        
                        <div class="flex items-center gap-1">
                          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/>
                            <circle cx="12" cy="10" r="3"/>
                          </svg>
                          <span>{evento.modalidad === 'online' ? 'En línea' : evento.modalidad === 'presencial' ? 'Presencial' : 'Híbrido'}</span>
                        </div>
                        
                        {#if evento.instructor_nombre}
                          <div class="flex items-center gap-1">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/>
                              <circle cx="9" cy="7" r="4"/>
                              <path d="M23 21v-2a4 4 0 0 0-3-3.87"/>
                              <path d="M16 3.13a4 4 0 0 1 0 7.75"/>
                            </svg>
                            <span>{evento.instructor_nombre}</span>
                          </div>
                        {/if}
                      </div>
                    </div>
                    
                    <!-- Sidebar derecho -->
                    <div class="flex flex-col items-end gap-3">
                      <!-- Badges -->
                      <div class="flex flex-col gap-2">
                        <span class="px-3 py-1 text-xs font-medium rounded-full {obtenerColorTipo(evento.tipo_evento)}">
                          {evento.tipo_evento}
                        </span>
                        {#if evento.es_gratuito}
                          <span class="px-3 py-1 text-xs font-bold bg-green-500 text-white rounded-full text-center">
                            GRATIS
                          </span>
                        {/if}
                      </div>
                      
                      <!-- Precio -->
                      <div class="text-right">
                        {#if evento.es_gratuito}
                          <span class="text-lg font-bold text-green-600">Gratis</span>
                        {:else}
                          {#if evento.precio_rebajado && evento.precio_rebajado < evento.precio}
                            <div class="text-xs text-gray-500 line-through">
                              {formatearPrecio(evento.precio)}
                            </div>
                            <div class="text-lg font-bold text-blue-600">
                              {formatearPrecio(evento.precio_rebajado)}
                            </div>
                          {:else}
                            <div class="text-lg font-bold text-blue-600">
                              {formatearPrecio(evento.precio)}
                            </div>
                          {/if}
                        {/if}
                      </div>
                      
                      <!-- Estadísticas -->
                      <div class="flex items-center gap-3 text-sm text-gray-500">
                        <div class="flex items-center gap-1">
                          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/>
                            <circle cx="9" cy="7" r="4"/>
                            <path d="M23 21v-2a4 4 0 0 0-3-3.87"/>
                            <path d="M16 3.13a4 4 0 0 1 0 7.75"/>
                          </svg>
                          <span>{evento.participantes_inscritos}</span>
                        </div>
                        
                        {#if evento.calificacion_promedio > 0}
                          <div class="flex items-center gap-1">
                            <svg class="w-4 h-4 fill-yellow-400 text-yellow-400" viewBox="0 0 24 24">
                              <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
                            </svg>
                            <span>{evento.calificacion_promedio.toFixed(1)}</span>
                          </div>
                        {/if}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {/each}
      </div>
    {/if}
    
    <!-- Paginación -->
    {#if totalPaginas > 1}
      <div class="flex items-center justify-center gap-2">
        <button
          class="px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
          disabled={paginaActual === 0}
          on:click={() => cambiarPagina(paginaActual - 1)}
        >
          Anterior
        </button>
        
        {#each Array(totalPaginas) as _, i}
          {#if i === 0 || i === totalPaginas - 1 || (i >= paginaActual - 2 && i <= paginaActual + 2)}
            <button
              class="px-3 py-2 text-sm font-medium rounded-lg {i === paginaActual ? 'bg-blue-600 text-white' : 'text-gray-700 bg-white border border-gray-300 hover:bg-gray-50'}"
              on:click={() => cambiarPagina(i)}
            >
              {i + 1}
            </button>
          {:else if i === paginaActual - 3 || i === paginaActual + 3}
            <span class="px-3 py-2 text-sm text-gray-500">...</span>
          {/if}
        {/each}
        
        <button
          class="px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
          disabled={paginaActual === totalPaginas - 1}
          on:click={() => cambiarPagina(paginaActual + 1)}
        >
          Siguiente
        </button>
      </div>
    {/if}
  {/if}
</div>

<style>
  .line-clamp-2 {
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }
</style>
