// src/lib/components/Inicio/HeroHome.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fly, scale } from 'svelte/transition';
  import { quintOut } from 'svelte/easing';
  import { goto } from '$app/navigation';

  export let mostrarModal: boolean;
  export let scrollToSection: (id: string) => void;

  let visible = false;

  onMount(() => {
    visible = true;
  });

  function irAlCursoEstrella() {
    goto('/curso-acordeon-desde-cero');
  }

  function irASimulador() {
    // Simulador próximamente
    alert('🎮 ¡Simulador Gaming en desarrollo! Será la experiencia más innovadora para aprender acordeón. ¡Lanzamiento en los próximos días!');
  }
</script>

<section class="hero-section">
  <!-- Fondo animado con partículas -->
  <div class="hero-particles">
    <div class="particles"></div>
  </div>
  
  <!-- Imagen de fondo con overlay -->
  <div class="hero-background">
    <img 
      src="/images/Home/Banner- Academia vallenata ONLINE.jpg" 
      alt="Academia Vallenata Background"
      class="hero-bg-image"
    />
  </div>
  
  <!-- Contenido principal -->
  <div class="hero-content">
    {#if visible}
      <!-- Badge de credibilidad -->
      <div in:fly="{{ y: -30, duration: 800, easing: quintOut }}" class="credibilidad-badge">
        🏆 #1 Academia de Acordeón Online • 5,000+ Estudiantes Transformados
      </div>

      <!-- Título principal -->
      <div in:fly="{{ y: 50, duration: 1000, easing: quintOut }}">
        <h1 class="hero-title">
          <span class="titulo-principal">Domina el Acordeón Vallenato</span>
          <span class="hero-subtitle">Como Un Verdadero Profesional</span>
        </h1>
      </div>
      
      <!-- Promesa de valor -->
      <div in:fly="{{ y: 50, duration: 1000, delay: 200, easing: quintOut }}">
        <p class="hero-description">
          🎵 De <strong>cero absoluto</strong> a tu <strong>primera canción en 7 días</strong> 
          <br>Con el método probado del Maestro <strong>Jesús González</strong> 
          <br>+ Simulador Gaming + Comunidad de 5,000+ acordeonistas
        </p>
      </div>

      <!-- Botones de acción -->
      <div in:fly="{{ y: 50, duration: 1000, delay: 300, easing: quintOut }}" class="hero-buttons">
        <button 
          on:click={irAlCursoEstrella}
          class="hero-btn-primary"
        >
          🚀 ¡EMPEZAR CURSO ESTRELLA!
          <span class="btn-subtitle">Primera canción en 7 días</span>
        </button>
        
        <button 
          on:click={irASimulador}
          class="hero-btn-gaming"
        >
          🎮 SIMULADOR PRÓXIMAMENTE
          <span class="btn-subtitle">Lanzamiento en días</span>
        </button>
      </div>
      
      <!-- Social proof -->
      <div in:scale="{{ start: 0, duration: 1000, delay: 500, easing: quintOut }}">
        <div class="hero-rating">
          <div class="rating-estrellas">
            <span class="rating-stars">⭐⭐⭐⭐⭐</span>
            <span class="rating-text">4.9/5 - 847 reseñas verificadas</span>
          </div>
          <div class="rating-estudiantes">
            <span class="numero-destacado">5,000+</span>
            <span>estudiantes activos</span>
          </div>
        </div>
      </div>
    {/if}
  </div>
  
  <!-- Scroll indicator -->
  <div class="scroll-indicator">
    <div class="scroll-mouse">
      <div class="scroll-dot"></div>
    </div>
    <span class="scroll-text">Descubre más</span>
  </div>
</section>

<style>
  .hero-section {
    position: relative;
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
    background: linear-gradient(135deg, #0f172a 0%, #1e293b 25%, #7c3aed 50%, #1e40af 75%, #0f172a 100%);
  }

  .hero-particles {
    position: absolute;
    inset: 0;
    opacity: 0.3;
  }

  .particles {
    width: 100%;
    height: 100%;
    background: url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23fbbf24' fill-opacity='0.1'%3E%3Ccircle cx='30' cy='30' r='2'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
    animation: particleFloat 25s linear infinite;
  }

  @keyframes particleFloat {
    0% { transform: translateY(0) rotate(0deg); }
    50% { transform: translateY(-20px) rotate(180deg); }
    100% { transform: translateY(0) rotate(360deg); }
  }

  .hero-background {
    position: absolute;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
  }

  .hero-bg-image {
    width: 100%;
    height: 100%;
    object-fit: cover;
    opacity: 0.2;
  }

  .hero-content {
    position: relative;
    z-index: 10;
    text-align: center;
    color: white;
    padding: 0 1rem;
    max-width: 1200px;
    margin: 0 auto;
  }

  /* Badge de credibilidad */
  .credibilidad-badge {
    display: inline-block;
    background: linear-gradient(135deg, #fbbf24, #f59e0b);
    color: #1f2937;
    padding: 0.8rem 2rem;
    border-radius: 50px;
    font-weight: 700;
    font-size: 0.9rem;
    margin-bottom: 2rem;
    box-shadow: 0 8px 25px rgba(251, 191, 36, 0.3);
    animation: pulseGlow 3s ease-in-out infinite;
  }

  @keyframes pulseGlow {
    0%, 100% { 
      transform: scale(1);
      box-shadow: 0 8px 25px rgba(251, 191, 36, 0.3);
    }
    50% { 
      transform: scale(1.02);
      box-shadow: 0 12px 35px rgba(251, 191, 36, 0.5);
    }
  }

  /* Títulos */
  .hero-title {
    margin-bottom: 2rem;
  }

  .titulo-principal {
    display: block;
    font-size: clamp(2.5rem, 8vw, 6rem);
    font-weight: 900;
    background: linear-gradient(135deg, #fbbf24 0%, #f59e0b 50%, #d97706 100%);
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    line-height: 1.1;
    margin-bottom: 0.5rem;
    text-shadow: 0 4px 8px rgba(0,0,0,0.3);
  }

  .hero-subtitle {
    display: block;
    font-size: clamp(1.5rem, 4vw, 3rem);
    font-weight: 700;
    color: #e2e8f0;
    line-height: 1.2;
  }

  /* Descripción */
  .hero-description {
    font-size: clamp(1.1rem, 3vw, 1.4rem);
    margin-bottom: 2rem;
    color: #cbd5e1;
    max-width: 800px;
    margin-left: auto;
    margin-right: auto;
    line-height: 1.6;
  }



  /* Botones principales */
  .hero-buttons {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
    justify-content: center;
    align-items: center;
    margin-bottom: 2.5rem;
    max-width: 500px;
    margin-left: auto;
    margin-right: auto;
  }

  .hero-btn-primary, .hero-btn-gaming {
    padding: 1.5rem 2.5rem;
    border-radius: 15px;
    border: none;
    cursor: pointer;
    font-weight: 800;
    font-size: 1.2rem;
    width: 100%;
    transition: all 0.3s ease;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .hero-btn-primary {
    background: linear-gradient(135deg, #dc2626 0%, #b91c1c 50%, #991b1b 100%);
    color: white;
    box-shadow: 0 10px 30px rgba(220, 38, 38, 0.4);
    animation: pulseRed 2s ease-in-out infinite;
  }

  .hero-btn-gaming {
    background: linear-gradient(135deg, #7c3aed 0%, #6366f1 50%, #4f46e5 100%);
    color: white;
    box-shadow: 0 10px 30px rgba(124, 58, 237, 0.4);
  }

  .hero-btn-primary:hover, .hero-btn-gaming:hover {
    transform: translateY(-5px) scale(1.02);
    box-shadow: 0 15px 40px rgba(220, 38, 38, 0.6);
  }

  .hero-btn-gaming:hover {
    box-shadow: 0 15px 40px rgba(124, 58, 237, 0.6);
  }

  @keyframes pulseRed {
    0%, 100% { 
      box-shadow: 0 10px 30px rgba(220, 38, 38, 0.4);
    }
    50% { 
      box-shadow: 0 15px 40px rgba(220, 38, 38, 0.7), 0 0 20px rgba(220, 38, 38, 0.3);
    }
  }

  .btn-subtitle {
    font-size: 0.8rem;
    font-weight: 400;
    opacity: 0.9;
    text-transform: none;
    letter-spacing: normal;
  }



  /* Social proof */
  .hero-rating {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
  }

  .rating-estrellas {
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .rating-stars {
    font-size: 1.5rem;
  }

  .rating-text {
    font-size: 1rem;
    font-weight: 600;
    color: #fbbf24;
  }

  .rating-estudiantes {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 1.1rem;
  }

  .numero-destacado {
    font-size: 2rem;
    font-weight: 900;
    background: linear-gradient(135deg, #fbbf24, #f59e0b);
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }

  /* Scroll indicator */
  .scroll-indicator {
    position: absolute;
    bottom: 2rem;
    left: 50%;
    transform: translateX(-50%);
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    animation: bounce 2s infinite;
  }

  .scroll-mouse {
    width: 1.5rem;
    height: 2.5rem;
    border: 2px solid rgba(255, 255, 255, 0.6);
    border-radius: 15px;
    display: flex;
    justify-content: center;
    align-items: flex-start;
    padding-top: 0.5rem;
  }

  .scroll-dot {
    width: 0.25rem;
    height: 0.75rem;
    background: rgba(255, 255, 255, 0.8);
    border-radius: 2px;
    animation: scrollDot 2s infinite;
  }

  .scroll-text {
    font-size: 0.8rem;
    color: rgba(255, 255, 255, 0.7);
    font-weight: 500;
  }

  @keyframes scrollDot {
    0%, 20% { opacity: 1; transform: translateY(0); }
    80%, 100% { opacity: 0; transform: translateY(1rem); }
  }

  @keyframes bounce {
    0%, 20%, 50%, 80%, 100% { transform: translateX(-50%) translateY(0); }
    40% { transform: translateX(-50%) translateY(-10px); }
    60% { transform: translateX(-50%) translateY(-5px); }
  }

  /* Responsive */
  @media (min-width: 640px) {
    .hero-buttons {
      flex-direction: row;
    }

    .rating-estrellas {
      flex-direction: row;
    }
  }

  @media (max-width: 480px) {
    .credibilidad-badge {
      font-size: 0.8rem;
      padding: 0.6rem 1.5rem;
    }

    .hero-btn-primary, .hero-btn-gaming {
      padding: 1.2rem 2rem;
      font-size: 1rem;
    }
  }
</style>

// src/componentes/Inicio/HeroHome.tsx
import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';

interface HeroHomeProps {
  mostrarModal: boolean;
  scrollToSection: (id: string) => void;
}

const HeroHome: React.FC<HeroHomeProps> = ({ scrollToSection }) => {
  const { t } = useTranslation();
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    setVisible(true);
  }, []);

  const irAlCursoEstrella = () => {
    window.location.href = '/curso-acordeon-desde-cero';
  };

  const irASimulador = () => {
    // Simulador próximamente
    alert('🎮 ¡Simulador Gaming en desarrollo! Será la experiencia más innovadora para aprender acordeón. ¡Lanzamiento en los próximos días!');
  };

  return (
    <>
      <section style={styles.heroSection}>
        {/* Fondo animado con partículas */}
        <div style={styles.heroParticles}>
          <div style={styles.particles}></div>
        </div>

        {/* Imagen de fondo con overlay */}
        <div style={styles.heroBackground}>
          <img
            src="/imagenes/Inicio/Home/Banner- Academia vallenata ONLINE.jpg"
            alt={t('hero.etiqueta')}
            style={styles.heroBgImage}
          />
        </div>

        {/* Contenido principal */}
        <div style={styles.heroContent}>
          {visible && (
            <>
              {/* Badge de credibilidad */}
              <div
                style={{
                  ...styles.credibilidadBadge,
                  animation: 'flyInFromTop 0.8s ease-out, pulseGlow 3s ease-in-out infinite'
                }}
              >
                🏆 {t('hero.etiqueta')} • 5,000+ {t('hero.estadisticas.estudiantes')}
              </div>

              {/* Título principal */}
              <div
                style={{
                  animation: 'flyInFromBottom 1s ease-out 0s'
                }}
              >
                <h1 style={styles.heroTitle}>
                  <span style={styles.tituloPrincipal}>{t('hero.tituloPrincipal')}</span>
                  <span style={styles.heroSubtitle}>{t('hero.subtitulo')}</span>
                </h1>
              </div>

              {/* Promesa de valor */}
              <div
                style={{
                  animation: 'flyInFromBottom 1s ease-out 0.2s both'
                }}
              >
                <p style={styles.heroDescription}>
                  <strong dangerouslySetInnerHTML={{ __html: t('hero.descripcion') }} />
                </p>
              </div>

              {/* Botones de acción */}
              <div
                className="hero-buttons"
                style={{
                  ...styles.heroButtons,
                  animation: 'flyInFromBottom 1s ease-out 0.3s both'
                }}
              >
                <button
                  className="hero-btn-primary"
                  onClick={irAlCursoEstrella}
                  style={{
                    ...styles.heroBtnPrimary,
                    animation: 'pulseRed 2s ease-in-out infinite'
                  }}
                >
                  🚀 {t('hero.boton.empezar')}
                  <span style={styles.btnSubtitle}>{t('hero.boton.subtexto')}</span>
                </button>

                <button
                  className="hero-btn-gaming"
                  onClick={irASimulador}
                  style={styles.heroBtnGaming}
                >
                  🎮 {t('hero.simuladorBoton.titulo')} {t('hero.simuladorBoton.subtitulo')}
                  <span style={styles.btnSubtitle}>{t('hero.simuladorBoton.lanzamiento')}</span>
                </button>
              </div>

              {/* Social proof */}
              <div
                style={{
                  animation: 'scaleIn 1s ease-out 0.5s both'
                }}
              >
                <div style={styles.heroRating}>
                  <div style={styles.ratingEstrellas}>
                    <span style={styles.ratingStars}>⭐⭐⭐⭐⭐</span>
                    <span style={styles.ratingText}>4.9/5 - 847 reseñas verificadas</span>
                  </div>
                  <div style={styles.ratingEstudiantes}>
                    <span style={styles.numeroDestacado}>5,000+</span>
                    <span>{t('hero.estadisticas.estudiantes')}</span>
                  </div>
                </div>
              </div>
            </>
          )}
        </div>

        {/* Scroll indicator */}
        <div style={styles.scrollIndicator}>
          <div style={styles.scrollMouse}>
            <div style={styles.scrollDot}></div>
          </div>
          <span style={styles.scrollText}>Descubre más</span>
        </div>
      </section>

      <style>{`
        @keyframes particleFloat {
          0% { transform: translateY(0) rotate(0deg); }
          50% { transform: translateY(-20px) rotate(180deg); }
          100% { transform: translateY(0) rotate(360deg); }
        }

        @keyframes pulseGlow {
          0%, 100% { 
            transform: scale(1);
            box-shadow: 0 8px 25px rgba(251, 191, 36, 0.3);
          }
          50% { 
            transform: scale(1.02);
            box-shadow: 0 12px 35px rgba(251, 191, 36, 0.5);
          }
        }

        @keyframes pulseRed {
          0%, 100% { 
            box-shadow: 0 10px 30px rgba(220, 38, 38, 0.4);
          }
          50% { 
            box-shadow: 0 15px 40px rgba(220, 38, 38, 0.7), 0 0 20px rgba(220, 38, 38, 0.3);
          }
        }

        @keyframes scrollDot {
          0%, 20% { opacity: 1; transform: translateY(0); }
          80%, 100% { opacity: 0; transform: translateY(1rem); }
        }

        @keyframes bounce {
          0%, 20%, 50%, 80%, 100% { transform: translateX(-50%) translateY(0); }
          40% { transform: translateX(-50%) translateY(-10px); }
          60% { transform: translateX(-50%) translateY(-5px); }
        }

        @keyframes flyInFromTop {
          from { transform: translateY(-30px); opacity: 0; }
          to { transform: translateY(0); opacity: 1; }
        }

        @keyframes flyInFromBottom {
          from { transform: translateY(50px); opacity: 0; }
          to { transform: translateY(0); opacity: 1; }
        }

        @keyframes scaleIn {
          from { transform: scale(0); opacity: 0; }
          to { transform: scale(1); opacity: 1; }
        }

        /* Media queries para botones responsivos */
        @media (max-width: 768px) {
          .hero-buttons {
            flex-direction: column !important;
          }
          
          .hero-btn-primary, .hero-btn-gaming {
            width: 100% !important;
            max-width: 100% !important;
            min-width: auto !important;
          }
        }

        @media (min-width: 769px) {
          .hero-buttons {
            flex-direction: row !important;
          }
        }
      `}</style>
    </>
  );
};

const styles = {
  heroSection: {
    position: 'relative' as const,
    minHeight: '100vh',
    width: '100%',
    maxWidth: '100vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 25%, #7c3aed 50%, #1e40af 75%, #0f172a 100%)',
    boxSizing: 'border-box' as const,
  },
  heroParticles: {
    position: 'absolute' as const,
    inset: '0',
    opacity: 0.3,
  },
  particles: {
    width: '100%',
    height: '100%',
    background: "url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23fbbf24' fill-opacity='0.1'%3E%3Ccircle cx='30' cy='30' r='2'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E\")",
    animation: 'particleFloat 25s linear infinite',
  },
  heroBackground: {
    position: 'absolute' as const,
    inset: '0',
    background: 'rgba(0, 0, 0, 0.5)',
  },
  heroBgImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
    opacity: 0.2,
  },
  heroContent: {
    position: 'relative' as const,
    zIndex: 10,
    textAlign: 'center' as const,
    color: 'white',
    padding: '0 1rem',
    maxWidth: '1200px',
    width: '100%',
    margin: '0 auto',
    boxSizing: 'border-box' as const,
  },
  credibilidadBadge: {
    display: 'inline-block',
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    color: '#1f2937',
    padding: '0.8rem 2rem',
    borderRadius: '50px',
    fontWeight: 700,
    fontSize: '0.9rem',
    marginBottom: '2rem',
    boxShadow: '0 8px 25px rgba(251, 191, 36, 0.3)',
  },
  heroTitle: {
    marginBottom: '2rem',
  },
  tituloPrincipal: {
    display: 'block',
    fontSize: 'clamp(2.5rem, 8vw, 6rem)',
    fontWeight: 900,
    background: 'linear-gradient(135deg, #fbbf24 0%, #f59e0b 50%, #d97706 100%)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    lineHeight: 1.1,
    marginBottom: '0.5rem',
    textShadow: '0 4px 8px rgba(0,0,0,0.3)',
  },
  heroSubtitle: {
    display: 'block',
    fontSize: 'clamp(1.5rem, 4vw, 3rem)',
    fontWeight: 700,
    color: '#e2e8f0',
    lineHeight: 1.2,
  },
  heroDescription: {
    fontSize: 'clamp(1.1rem, 3vw, 1.4rem)',
    marginBottom: '2rem',
    color: '#cbd5e1',
    maxWidth: '800px',
    marginLeft: 'auto',
    marginRight: 'auto',
    lineHeight: 1.6,
  },
  heroButtons: {
    display: 'flex',
    flexDirection: 'row' as const,
    gap: '1.5rem',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '2.5rem',
    maxWidth: '100%',
    width: '100%',
    marginLeft: 'auto',
    marginRight: 'auto',
    padding: '0 0.5rem',
    boxSizing: 'border-box' as const,
    flexWrap: 'wrap' as const,
  },
  heroBtnPrimary: {
    padding: '1.5rem 1rem',
    borderRadius: '15px',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 800,
    fontSize: 'clamp(1rem, 4vw, 1.2rem)',
    width: 'auto',
    minWidth: '280px',
    flex: '1',
    maxWidth: '400px',
    transition: 'all 0.3s ease',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '0.5rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    boxSizing: 'border-box' as const,
    overflow: 'hidden',
    background: 'linear-gradient(135deg, #dc2626 0%, #b91c1c 50%, #991b1b 100%)',
    color: 'white',
    boxShadow: '0 10px 30px rgba(220, 38, 38, 0.4)',
  },
  heroBtnGaming: {
    padding: '1.5rem 2rem',
    borderRadius: '15px',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 800,
    fontSize: 'clamp(1rem, 4vw, 1.2rem)',
    width: 'auto',
    minWidth: '280px',
    flex: '1',
    maxWidth: '400px',
    transition: 'all 0.3s ease',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '0.5rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    boxSizing: 'border-box' as const,
    overflow: 'hidden',
    background: 'linear-gradient(135deg, #7c3aed 0%, #6366f1 50%, #4f46e5 100%)',
    color: 'white',
    boxShadow: '0 10px 30px rgba(124, 58, 237, 0.4)',
  },
  btnSubtitle: {
    fontSize: '0.8rem',
    fontWeight: 400,
    opacity: 0.9,
    textTransform: 'none' as const,
    letterSpacing: 'normal',
  },
  heroRating: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '1rem',
  },
  ratingEstrellas: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  ratingStars: {
    fontSize: '1.5rem',
  },
  ratingText: {
    fontSize: '1rem',
    fontWeight: 600,
    color: '#fbbf24',
  },
  ratingEstudiantes: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '1.1rem',
  },
  numeroDestacado: {
    fontSize: '2rem',
    fontWeight: 900,
    background: 'linear-gradient(135deg, #fbbf24, #f59e0b)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  scrollIndicator: {
    position: 'absolute' as const,
    bottom: '2rem',
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '0.5rem',
    animation: 'bounce 2s infinite',
  },
  scrollMouse: {
    width: '1.5rem',
    height: '2.5rem',
    border: '2px solid rgba(255, 255, 255, 0.6)',
    borderRadius: '15px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingTop: '0.5rem',
  },
  scrollDot: {
    width: '0.25rem',
    height: '0.75rem',
    background: 'rgba(255, 255, 255, 0.8)',
    borderRadius: '2px',
    animation: 'scrollDot 2s infinite',
  },
  scrollText: {
    fontSize: '0.8rem',
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: 500,
  },
};

export default HeroHome;
